package com.project.xy.tomatotime.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.project.xy.tomatotime.Entity.Plan;
import com.project.xy.tomatotime.Entity.Schedule;
import com.project.xy.tomatotime.Entity.Occupied;

import com.project.xy.tomatotime.greendao.PlanDao;
import com.project.xy.tomatotime.greendao.ScheduleDao;
import com.project.xy.tomatotime.greendao.OccupiedDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig planDaoConfig;
    private final DaoConfig scheduleDaoConfig;
    private final DaoConfig occupiedDaoConfig;

    private final PlanDao planDao;
    private final ScheduleDao scheduleDao;
    private final OccupiedDao occupiedDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        planDaoConfig = daoConfigMap.get(PlanDao.class).clone();
        planDaoConfig.initIdentityScope(type);

        scheduleDaoConfig = daoConfigMap.get(ScheduleDao.class).clone();
        scheduleDaoConfig.initIdentityScope(type);

        occupiedDaoConfig = daoConfigMap.get(OccupiedDao.class).clone();
        occupiedDaoConfig.initIdentityScope(type);

        planDao = new PlanDao(planDaoConfig, this);
        scheduleDao = new ScheduleDao(scheduleDaoConfig, this);
        occupiedDao = new OccupiedDao(occupiedDaoConfig, this);

        registerDao(Plan.class, planDao);
        registerDao(Schedule.class, scheduleDao);
        registerDao(Occupied.class, occupiedDao);
    }
    
    public void clear() {
        planDaoConfig.clearIdentityScope();
        scheduleDaoConfig.clearIdentityScope();
        occupiedDaoConfig.clearIdentityScope();
    }

    public PlanDao getPlanDao() {
        return planDao;
    }

    public ScheduleDao getScheduleDao() {
        return scheduleDao;
    }

    public OccupiedDao getOccupiedDao() {
        return occupiedDao;
    }

}
